// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// /// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtqJjv0VP_xZo9QL1WavhK9ADFI2cFe8',
    appId: '1:323321818586:web:ed491055429cfa07a924e3',
    messagingSenderId: '323321818586',
    projectId: 'watery-dc101',
    authDomain: 'watery-dc101.firebaseapp.com',
    storageBucket: 'watery-dc101.appspot.com',
    measurementId: 'G-3ZLC8P4BFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXqebnfkfDSKsX5yxTkoSJvsRMGeHAK80',
    appId: '1:323321818586:android:1c09773ac6da8a5ba924e3',
    messagingSenderId: '323321818586',
    projectId: 'watery-dc101',
    storageBucket: 'watery-dc101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOJ85U9r7ychaMLkKVHl9ikyD1OSyf_Yg',
    appId: '1:323321818586:ios:5f8d11ca32ace749a924e3',
    messagingSenderId: '323321818586',
    projectId: 'watery-dc101',
    storageBucket: 'watery-dc101.appspot.com',
    iosBundleId: 'com.example.watery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOJ85U9r7ychaMLkKVHl9ikyD1OSyf_Yg',
    appId: '1:323321818586:ios:5f8d11ca32ace749a924e3',
    messagingSenderId: '323321818586',
    projectId: 'watery-dc101',
    storageBucket: 'watery-dc101.appspot.com',
    iosBundleId: 'com.example.watery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvtqJjv0VP_xZo9QL1WavhK9ADFI2cFe8',
    appId: '1:323321818586:web:f3cea7f22751f313a924e3',
    messagingSenderId: '323321818586',
    projectId: 'watery-dc101',
    authDomain: 'watery-dc101.firebaseapp.com',
    storageBucket: 'watery-dc101.appspot.com',
    measurementId: 'G-12L4VBK1FN',
  );
}
